version: '3'
services:
  # Descrição: Orquestrador do(s) broker(s)
  # Responsabilidade: Eleição do broker, balanceamento, etc.
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - fluxo-caixa-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Broker / hosts / server
  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - fluxo-caixa-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Serviço de gerenciamento e visualização do(s) Broker(s) Kafka via browser
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - fluxo-caixa-network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  # Base de dados PostgresSQL
  postgressql:
    image: postgres:11-alpine

networks: 
  fluxo-caixa-network:
    driver: bridge  